/**
 * Initial Sensor Station Definitions for Indian Coalfields (SIH26025)
 */
export const DEFAULT_STATIONS = [
  // Jharia Coalfield (Jharkhand) - High Risk Prime Monitoring Zone
  { id: "S-001", name: "NodeMCU Primary Telemetry Station S-001", mine_id: "jharkhand", lat: 23.7512, lng: 86.4215, status: "SAFE", tilt: 1.2, displacement: 2.4, vibration: "Normal", crack_status: "Normal", battery: 98, signal_rssi: -58, risk_score: 18, panel: "Longwall Face, Shaft 1", is_hardware: true },
  { id: "S-002", name: "Surface Station S-002", mine_id: "jharkhand", lat: 23.7548, lng: 86.4262, status: "SAFE", tilt: 0.9, displacement: 1.8, vibration: "Normal", crack_status: "Normal", battery: 94, signal_rssi: -64, risk_score: 14, panel: "North Panel, Sector A", is_hardware: false },
  { id: "S-003", name: "Goaf Edge Station S-003", mine_id: "jharkhand", lat: 23.7485, lng: 86.4180, status: "SAFE", tilt: 1.5, displacement: 3.1, vibration: "Normal", crack_status: "Normal", battery: 91, signal_rssi: -70, risk_score: 24, panel: "Goaf Area, Pillar 14", is_hardware: false },
  { id: "S-004", name: "Incline Boundary S-004", mine_id: "jharkhand", lat: 23.7570, lng: 86.4230, status: "SAFE", tilt: 1.1, displacement: 2.0, vibration: "Normal", crack_status: "Normal", battery: 89, signal_rssi: -66, risk_score: 16, panel: "Shaft 2 Incline", is_hardware: false },
  { id: "S-005", name: "Railway Pillar S-005", mine_id: "jharkhand", lat: 23.7460, lng: 86.4290, status: "SAFE", tilt: 0.8, displacement: 1.5, vibration: "Normal", crack_status: "Normal", battery: 95, signal_rssi: -60, risk_score: 12, panel: "Surface Rail Corridor", is_hardware: false },
  { id: "S-006", name: "Main Ventilation Node S-006", mine_id: "jharkhand", lat: 23.7530, lng: 86.4150, status: "SAFE", tilt: 1.3, displacement: 2.8, vibration: "Normal", crack_status: "Normal", battery: 93, signal_rssi: -68, risk_score: 21, panel: "Air Intake Shaft North", is_hardware: false },
  { id: "S-007", name: "Subsidence Trough Watch S-007", mine_id: "jharkhand", lat: 23.7498, lng: 86.4245, status: "WARNING", tilt: 2.8, displacement: 7.2, vibration: "Normal", crack_status: "Detected", battery: 88, signal_rssi: -72, risk_score: 64, panel: "Longwall Face, Shaft 2", is_hardware: false },
  { id: "S-008", name: "Barrier Pillar Station S-008", mine_id: "jharkhand", lat: 23.7562, lng: 86.4310, status: "SAFE", tilt: 0.7, displacement: 1.4, vibration: "Normal", crack_status: "Normal", battery: 96, signal_rssi: -62, risk_score: 11, panel: "Barrier Pillar East", is_hardware: false },
  { id: "S-009", name: "Sub-surface Acoustic Node S-009", mine_id: "jharkhand", lat: 23.7445, lng: 86.4205, status: "SAFE", tilt: 1.4, displacement: 2.6, vibration: "Normal", crack_status: "Normal", battery: 85, signal_rssi: -75, risk_score: 22, panel: "Old Workings Seam XI", is_hardware: false },
  { id: "S-010", name: "Overburden Stress Node S-010", mine_id: "jharkhand", lat: 23.7585, lng: 86.4190, status: "SAFE", tilt: 1.0, displacement: 1.9, vibration: "Normal", crack_status: "Normal", battery: 90, signal_rssi: -67, risk_score: 15, panel: "Overburden Ridge North", is_hardware: false },
  { id: "S-011", name: "Haul Road Surface Node S-011", mine_id: "jharkhand", lat: 23.7510, lng: 86.4340, status: "SAFE", tilt: 0.9, displacement: 1.7, vibration: "Normal", crack_status: "Normal", battery: 92, signal_rssi: -65, risk_score: 14, panel: "Central Haul Track", is_hardware: false },
  { id: "S-012", name: "Goaf Deformation Node S-012", mine_id: "jharkhand", lat: 23.7475, lng: 86.4260, status: "CRITICAL", tilt: 5.4, displacement: 15.8, vibration: "High", crack_status: "Severe", battery: 82, signal_rssi: -79, risk_score: 86, panel: "Goaf Area, Panel 3", is_hardware: false },

  // Talcher Coalfield (Odisha)
  { id: "S-013", name: "South Balanda Seam S-013", mine_id: "odisha", lat: 20.9520, lng: 85.1950, status: "SAFE", tilt: 0.8, displacement: 1.6, vibration: "Normal", crack_status: "Normal", battery: 97, signal_rssi: -61, risk_score: 13, panel: "Open Cast Highwall Balanda", is_hardware: false },
  { id: "S-014", name: "Nandira Incline S-014", mine_id: "odisha", lat: 20.9480, lng: 85.1990, status: "SAFE", tilt: 1.1, displacement: 2.2, vibration: "Normal", crack_status: "Normal", battery: 94, signal_rssi: -65, risk_score: 17, panel: "Underground Panel 2", is_hardware: false },
  { id: "S-015", name: "Brahmani Buffer Station S-015", mine_id: "odisha", lat: 20.9560, lng: 85.2040, status: "WARNING", tilt: 2.6, displacement: 6.9, vibration: "Elevated", crack_status: "Normal", battery: 89, signal_rssi: -71, risk_score: 58, panel: "Surface Bowl, Sector D", is_hardware: false },
  { id: "S-016", name: "Jagannath Colliery Edge S-016", mine_id: "odisha", lat: 20.9430, lng: 85.1910, status: "SAFE", tilt: 0.9, displacement: 1.8, vibration: "Normal", crack_status: "Normal", battery: 93, signal_rssi: -67, risk_score: 14, panel: "Dip Side Barrier", is_hardware: false },

  // Korba Coalfield (Chhattisgarh)
  { id: "S-017", name: "Gevra Overburden S-017", mine_id: "chhattisgarh", lat: 22.3480, lng: 82.6850, status: "SAFE", tilt: 1.0, displacement: 2.1, vibration: "Normal", crack_status: "Normal", battery: 95, signal_rssi: -63, risk_score: 16, panel: "Gevra Deep Cut", is_hardware: false },
  { id: "S-018", name: "Kusmunda Longwall Node S-018", mine_id: "chhattisgarh", lat: 22.3420, lng: 82.6920, status: "SAFE", tilt: 1.3, displacement: 2.7, vibration: "Normal", crack_status: "Normal", battery: 91, signal_rssi: -69, risk_score: 20, panel: "Continuous Miner Panel 4", is_hardware: false },
  { id: "S-019", name: "Dipka Fault Line S-019", mine_id: "chhattisgarh", lat: 22.3550, lng: 82.6780, status: "SAFE", tilt: 1.4, displacement: 2.9, vibration: "Normal", crack_status: "Normal", battery: 90, signal_rssi: -72, risk_score: 23, panel: "Fault Transition Zone", is_hardware: false },
  { id: "S-020", name: "Manikpur Surface Strain S-020", mine_id: "chhattisgarh", lat: 22.3390, lng: 82.7010, status: "SAFE", tilt: 0.7, displacement: 1.3, vibration: "Normal", crack_status: "Normal", battery: 98, signal_rssi: -59, risk_score: 10, panel: "Eastern Boundary Pillar", is_hardware: false },

  // Raniganj Coalfield (West Bengal)
  { id: "S-021", name: "Dishergarh Seam Watch S-021", mine_id: "westbengal", lat: 23.6820, lng: 86.9750, status: "SAFE", tilt: 1.1, displacement: 2.3, vibration: "Normal", crack_status: "Normal", battery: 92, signal_rssi: -66, risk_score: 17, panel: "Dishergarh Shaft 3", is_hardware: false },
  { id: "S-022", name: "Sanctoria Goaf Strain S-022", mine_id: "westbengal", lat: 23.6780, lng: 86.9810, status: "SAFE", tilt: 1.6, displacement: 3.4, vibration: "Normal", crack_status: "Normal", battery: 87, signal_rssi: -74, risk_score: 26, panel: "Goaf Caving Zone 1", is_hardware: false },
  { id: "S-023", name: "Sripur Old Workings S-023", mine_id: "westbengal", lat: 23.6890, lng: 86.9690, status: "SAFE", tilt: 1.2, displacement: 2.5, vibration: "Normal", crack_status: "Normal", battery: 93, signal_rssi: -68, risk_score: 19, panel: "Abandoned Seam Roof", is_hardware: false },
  { id: "S-024", name: "Asansol Suburb Buffer S-024", mine_id: "westbengal", lat: 23.6740, lng: 86.9880, status: "SAFE", tilt: 0.6, displacement: 1.1, vibration: "Normal", crack_status: "Normal", battery: 99, signal_rssi: -56, risk_score: 9, panel: "Surface Urban Buffer", is_hardware: false }
];
